---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-tower-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-tower-operator
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "secrets"
      - "events"
    verbs: ["*"]
  - apiGroups:
      - jetstream.nats.io
    resources:
      - accounts
      - accounts/status
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-tower-operator
subjects:
  - kind: ServiceAccount
    name: nats-tower-operator-service-account
roleRef:
  kind: ClusterRole
  name: nats-tower-operator
  apiGroup: rbac.authorization.k8s.io
