apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats-tower-operator
resources:
- namespace.yaml
- operator.deployment.yaml

configMapGenerator:
  - name: nats-tower-operator-config
    literals:
      - NATS_TOWER_API_TOKEN_PATH=/secrets/nats-tower-api-token