apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-tower-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-tower-operator
  template:
    metadata:
      labels:
        app: nats-tower-operator
    spec:
      serviceAccountName: nats-tower-operator-service-account
      containers:
        - name: nats-tower-operator
          image: "ghcr.io/nats-tower/nats-tower-operator:main"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - secretRef:
                name: nats-tower-operator-secrets
            - configMapRef:
                name: nats-tower-operator-config
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
      volumes:
        - name: config-volume
          configMap:
            name: nats-tower-operator-config